import './globals.css';
import Footer from '@/app/footer';
import { IBM_Plex_Sans, Merriweather } from 'next/font/google';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const IBM_Plex_SansFont = IBM_Plex_Sans({
	variable: '--IBM-Plex-Sans',
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
});

const MerriweatherFont = Merriweather({
	weight: ['300', '400', '700', '900'],
	variable: '--merriweather',
	subsets: ['latin'],
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className={`${IBM_Plex_SansFont.variable} ${MerriweatherFont.variable}`}
		>
			<body
				className={'bg-white min-h-screen flex justify-center items-center'}
			>
				{children}
				<Footer />
			</body>
		</html>
	);
}
